import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import { NavHeader } from './components/NavHeader'
import { TopPage } from './components/TopPage'
import { Footer } from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Landing Page Nextjs',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TopPage />
        <NavHeader />
        {children}
        <Footer />
      </body>
    </html>
  )
}
